### PR TITLE
FIX: Float to Number, header added

### PR DESCRIPTION
**Pull request by ddmitrii**
Header machine added
Float changed to Number due Crate error

### CODE REVIEW

**Comment by jgato** [comment]
I think it is better to also support float. Please, could you keep the if float option and adding the new number type?

**Comment by ddmitrii** [comment]
Crate allows float, but according to http://fiware.github.io/context.Orion/api/v2/latest/
originally we can use 
"If value is a number, then type Number is used"

So sorry for commit message, even Integer is not correct. Orion stores data as it is, so we can use any type of data, but for federation mode and v2/notifications, it' s better to fix every type as float/integer/long and so on to Number.

**Comment by ddmitrii** [comment]
Yes! But the list of available types it pretty big (geo:json as example), so i think it's better for now to fix scripts according to current types and then think about others

**Comment by jgato** [comment]
ok, in the future maybe we will need to diferentiate between original type and the type you want to use in NGSI

**Pull request merged**
